name: sf_env
channels:
- snowflake
dependencies:
- snowflake-native-apps-permission
- python = "3.9"
- pandas = "^2.0.1"
- loguru = "^0.7.2"
- protobuf = "5.26.1"
- pydantic = "^2.6.4"
- PyYAML = "^6.0.1"
- ruamel.yaml = "^0.18.6"
- tqdm = "^4.66.2"
- pyarrow = ">=10.0.1,<10.1.0"
- sqlglot = "^23.17.0"
- streamlit = "^1.37.1"
- numpy = "^1.24.4"
- python-dotenv = "^1.0.1"
- urllib3 = "^1.26.19"
- requests = "^2.32.3"
- mypy = "^1.9.0"
- black = "^24.3.0"
- isort = "^5.13.2"
- flake8 = "^7.0.0"
- pytest = "^8.1.1"
- types-pyyaml = "^6.0.12.20240311"
- types-protobuf = "^4.24.0.20240311"
- pip-licenses = "^4.4.0"
- grpcio-tools = "1.64.1"